### ISSUE TITLE
Fix broken URL in Sample collection device description

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#153]
http://purl.obolibrary.org/obo/GENEPIO_0002094 in "Sample collection device" description is broken. I tried looking for a replacement but could not find an obvious one. I could use help from @mslarae13 here.

**Comment by turbomam** [comment]
From [mixs_modified_slots](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=770915920&range=12:12). Note that mentioning these terms with the exact wording and capitalization from the DH label, or as it appears in SNTC is very much appreciated, since related variants may be present

`mixs_modified_slots` has a term with the `slot` name 'sample_collection_dev', the SNTC `name` 'sample collection device' (which becomes the LinkML `title` and the DH column header) and the informally associated MIxS term `samp_collec_device`.  _Most of that will be dramtically clarified when we move from SNTC to [schemasheets](https://github.com/linkml/schemasheets)._

We statically imported the reference to `http://purl.obolibrary.org/obo/GENEPIO_0002094` from MIxS.

See https://github.com/GenEpiO/genepio/issues/36

**Comment by turbomam** [comment]
Web resolution in OntoBee temporarily broken. I recommend leaving the description as is.

**Comment by pkalita-lbl** [comment]
Mark recommended leaving the description as-is. If there needs to be further updates to this slot's description please open a new issue in the `submission-schema` repo. Closing.
