### ISSUE TITLE
Rename "NMDC fields esp. GOLD paths" to "NMDC"

### ISSUE THREAD

**Issue by pvangay** [microbiomedata/DataHarmonizer#164]
"NMDC fields esp. GOLD paths" is not a clear section name. 

I suggest putting all of these terms below into a section called “NMDC”. Please review @mslarae13 and reassign to @turbomam if you think this seems reasonable.
- Globally Unique ID
- Sample Name
- Environmental package
- Analysis/Data Type
- Sample linkage
- GOLD path terms

**Comment by turbomam** [comment]
Yeah, I can see how 'NMDC fields esp. GOLD paths' isn't the best section name. I'm responsible or that.

I don't think we should claim any column comes from NMDC unless it really comes from NMDC and is being used entirely as-is, including the term `title`, which is applied as the column header. However, that statement of mine is not enforced by any software at this point. 

_Technically you can put any column in any section. I used to enforce sections based on the prefix portion of the term's id, among other factors, but that was disabled in favor of the [Sections_order tab](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1759225432) and the section columns in other tabs. ([example](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=541445893&range=D:D))_

Most of the terms listed above are not NMDC terms, or not being used as-is (which may mean that we should modify the NMDC schema.) See https://microbiomedata.github.io/nmdc-schema/

## Specifics:

### Globally Unique ID
Soil-NMDC-Template_Compiled defines 'Globally Unique ID' on the [biosample_identification_slots tab](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1627022346&range=2:2), so it is definitely not an as-is NMDC term.

Soil-NMDC-Template_Compiled has informal comments suggesting that 'Globally Unique ID' is a [replacement for MIxS' `source_mat_id`](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=877213473&range=D1031:H1031) and is a [replacement for NMDC's `id` term](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1974870456&range=C25:F25) (which makes more sense to me)

### sample name (note the capitalization)
Defined in [biosample_identification_slots tab ](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1627022346&range=3:3)

I don't see any notes about what NMDC column it might be related to

### environmental package (note the capitalization)

This is being taken from the [biosample_identification_slots tab](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1627022346&range=4:4). NMDC **does** have an [env_package](https://microbiomedata.github.io/nmdc-schema/env_package/#slot-env_package) term that appears in `nmdc-schema/src/schema/mixs.yaml` via the old MIxS v5 import, but its (implicit) range is string, whereas SNTC implements the range a an enum (although [it only has one permissible value in the `soil_emsl_jgi_mg` template, 'soil'](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1998417510&range=A89:C89)). 

_The [MIxS as LinkML YAML](https://github.com/turbomam/mixs-source) that @cmungall and I derive from the MIxS v6 Google Sheet no longer contains an `env_package` term._

### Analysis/Data Type
This is defined on the [biosample_identification_slots tab](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1627022346&range=5:5) which informally says that `investigation_type` is associated.

The NMDC schema **does** have an [investigation_type](https://microbiomedata.github.io/nmdc-schema/investigation_type/) term, but its (implicit) range is string, whereas SNTC implements the range a an [enum](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1998417510&range=A2:C5). Note that, in the SNTC Google Sheet, this term has a [slot name of 'analysis_type' but a Column Header of 'Analysis/Data Type'](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1627022346&range=C5:F5), which is implemented as its LinkML `title`.

### sample linkage (note the capitalization)

Defined on the [biosample_identification_slots](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1627022346&range=6:6) tab.

No `Associated Term` is asserted.

The NMDC schema has [link_addit_analys](https://microbiomedata.github.io/nmdc-schema/link_addit_analys/#slot-link_addit_analys). Maybe there are other related NMDC or MIxS terms. I haven't researched any further yet. 

### GOLD path terms

These are defined in the NMDC schema, but with an (implicit) string range. In the spirit of the `mixs_modified_slots` tab, I reimplemented these in the [biosample_identification_slots tab](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1627022346&range=7:11) in order to apply enum ranges ([partial example](https://docs.google.com/spreadsheets/d/1pSmxX6XGOxmoA7S7rKyj5OaEl3PmAl4jAOlROuNHrU0/edit?pli=1#gid=1998417510&range=64:88))

**Comment by pvangay** [comment]
Agree with the statements that these terms are not really "NMDC" terms. Possibly leaving them in an unnamed section until we flesh the below out more?

> Globally Unique ID

Long-term, per conversations about NMDC minting IDs, this should be a column that is generated by the NMDC and should be non-editable by the user. 

> sample name

If I remember correctly, I thought this was a term that will be in MIxS v6 (so perhaps we are anticipating it by adding it now). it's a very useful term from a user perspective.

> environmental package 

Related to microbiomedata/DataHarmonizer#168 -- there are a number of terms like these (including the JGI terms) that should be prefilled from another source and possibly non-editable by the user. 

> Analysis/Data Type

I see this useful for determining what preparation/processing metadata to request from the user (i.e. DNA terms from JGI).

> sample linkage

I recall there being a discussion about parent sample ID and allowable usages of MIxS's source_mat_id. I believe this might be where this term came from but this needs to be more fleshed out because it is not very usable as is. See microbiomedata/submission-schema#211 

> GOLD path terms

These terms technically come from GOLD / IMG / JGI, so yes, agreed they are not really NMDC terms.

**Comment by pkalita-lbl** [comment]
This section is now called "Sample ID". If that needs to be changed, please open a new issue in the `submission-schema` repo.
